name = "Breadwinners"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9e02fffd516768b1cf51ddd553e7e2a06d3976618080c25cd0a4eee1a61e8cb"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
