name = "Craftpunk Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd12f38018e9c0fcca6522b09742ae880206f2df0cef811bb0e3561286ef7b5e"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
